version: '3.4'

services:
  identityserversystem:
    image: identityserversystem
    build:
      context: ./IdentityServerSystem
      dockerfile: Dockerfile
    ports:
        - "6005:80"
    networks:
        - outside 
networks:
  outside:
    external:
      name: hahaxi_net